### PR TITLE
[#51] Added an ensureIndexes(boolean) method 

### LINKED ISSUE #51: MongoTokenStore index should be able to skip ensureIndexes()
### Enhancement Description

In controlled environments, the application mongodb user has no permissions to create collections or indexes, and in those cases, collection and indexes should be created before hand. I have a requirement to deploy in one of those environments, but the **MongoTokenStore** is always trying to create an index, thus making the application fail at startup due to permissions denied.

### Current Behaviour

When creating a **MongoTokenStore** via the Builder, it always runs the **ensureIndexes()** method, which tries to create an index for the tracking token collection. In my use case, this causes an error and the application fails on startup.

### Wanted Behaviour

I want to be able to configure in the builder, whether if I want the indexes being created by the application on runtime (as the default behavior it now has) or skip the index creation, as it was created before running the application.

### Possible Workarounds

In the **MongoTokenStore** builder, add a method 

```
public Builder ensureIndexes(boolean ensureIndexes){
...
}
```
Where we can configure this behavior.

### PR DESCRIPTION
**Pull request by erikrz**
To let the user decide whether to have the `MongoTokenStore` created indexes by itself, or have the developer be responsible for them.
This pull request resolves #51.

### CODE REVIEW

**Comment by lfgcampos** [comment]
hey @erikrz, I've pushed some missing changes to our master which should fix the build.
Do you mind rebasing/merging?

**Review by smcvb — APPROVED** [review]
Looks good to me :+1:

**Review by lfgcampos — APPROVED** [review]
LGTM

**Comment by smcvb** [comment]
Ignoring the Java11+Sonar build for now, as it fails due to credential issues with [GitHub Actions / SonarCloud].

**Pull request merged**
